### ISSUE TITLE
After upgrading to Flutter 2.5.0, facing deprecated message

### ISSUE THREAD

**Issue by ahaneef29** [ko2ic/image_downloader#107]
Flutter **2.5.0** • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4cc385b4b8 (27 hours ago) • 2021-09-07 23:01:49 -0700
Engine • revision f0826da7ef
Tools • Dart **2.14.0**

The plugin **image_downloader** uses a **deprecated version of the Android embedding.**
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

**Comment by Morena96** [comment]
same issue..

**Comment by mrgnhnt96** [comment]
Any update when this is going to be fixed?

**Comment by remi-martin** [comment]
same

**Comment by williamzheng0711** [comment]
same issue

**Comment by sushantdhumal** [comment]
Same issue

**Comment by ko2ic** [comment]
Sorry for the delay.
It's released!
