### ISSUE TITLE
Unexpectedly found nil while implicitly unwrapping an Optional value

### ISSUE THREAD

**Issue by scatboy777** [ko2ic/image_downloader#114]
Hello,

I am getting the following error when downloading an image. 

The code looks like this:
String url = ".....";
 ImageDownloader.downloadImage(url);

Error is and the application crash immedialety:
**image_downloader[/SwiftImageDownloaderPlugin.swift:397](): Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value**

I am using image_downloader: ^0.31.0

Any help will be appreciated.
Kind regards,
Olivier

**Comment by scatboy777** [comment]
I found workaround

**Comment by gaurang4** [comment]
What workaround you found can you please help me to fix this.

Thanks
