### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by imalphainc** [ko2ic/image_downloader#131]
e: C:\Users\PRINCE\AppData\Local\Pub\Cache\hosted\pub.dev\image_downloader-0.31.0\android\src\main\kotlin\com\ko2ic\imagedownloader\ImageDownloaderPlugin.kt: (332, 17): 'when' expression must be exhaustive, add necessary 'is Pending', 'is Successful' branches or 'else' branch instead

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':image_downloader:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 23s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by imalphainc** [comment]
Problem Solved
i Updated android/build.gradle

ext.kotlin_version = '1.6.10'

**Comment by 8thgencore** [comment]
@ko2ic it is possible to solve this problem for new versions of kotlin?

**Comment by funjay** [comment]
I think the version in git that has the fix is not yet released to pub, do i added the git url directly to my pubspec, that was my current fix.. hope it helps

**Comment by fabioselau077** [comment]
You are right.
I added the repo link directly in the pub and it worked.
Thanks for the tip.

```
  image_downloader:
    git:
      url: https://github.com/ko2ic/image_downloader
```

**Comment by Paradox2405** [comment]
> You are right. I added the repo link directly in the pub and it worked. Thanks for the tip.
> 
> ```
>   image_downloader:
>     git:
>       url: https://github.com/ko2ic/image_downloader
> ```

this worked as of now. Thanks.
