### ISSUE TITLE
On android when the permission 'Deny' pressed, await ImageDownloader.downloadImage never returns.

### ISSUE THREAD

**Issue by wonsuyon** [ko2ic/image_downloader#15]
I appreciate for this package.

Everything works fine except the 'Deny' event on android. (tested on 8.0)
(also happens with this example)

On iOS returning null works ok.

Any solution? thanks.

**Comment by ko2ic** [comment]
@wonsuyon Thank you for the information.

You're right. This is a bug. I will fix it soon.

**Comment by ko2ic** [comment]
@wonsuyon 
Fixed. Please use v0.12.1.

**Comment by wonsuyon** [comment]
Thank you, works fine.
