### ISSUE TITLE
Detect no internet connection and not-responding URL

### ISSUE THREAD

**Issue by wonsuyon** [ko2ic/image_downloader#16]
I've tested on android.
and need a detection, timeout for enhancement, thanks.

**Comment by wonsuyon** [comment]
can't catch 404
the app crashes

**Comment by ko2ic** [comment]
It can be implemented in your application.

```
        imageId = await ImageDownloader.downloadImage("https://raw.githubusercontent.com/wiki/ko2ic/image_downloader/images/flutter_no.png").catchError((error) {
          print(error);
        }).timeout(Duration(seconds: 10), onTimeout: () {
          print("timeout");
        });
```

**Comment by ko2ic** [comment]
In addition,  added error handling in v13.0.0.

* HTTP error code can be acquired from PlatformException.
* The file in case of error was deleted on Android.

**Comment by wonsuyon** [comment]
Thank you for your quick update.
The dart timeout() gives us a good timeout except the permission dialog appears.
and the app doesn't crash. we can catch the error.
