### ISSUE TITLE
IOS build error

### ISSUE THREAD

**Issue by iwasnothing** [ko2ic/image_downloader#2]
flutter/.pub-cache/hosted/pub.dartlang.org/image_downloader-0.9.1/ios/Classes/ImageDownloaderPlugin.m:2:9: fatal error: 'image_downloader/image_downloader-Swift.h' file not found
    #import <image_downloader/image_downloader-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

Could not build the application for the simulator.
Error launching application on iPhone XR.

**Comment by ko2ic** [comment]
It is closed because there are no reports from other users.
Please make another issue if the same problem comes up.

**Comment by ImaginationRoom** [comment]
We have this problem as well.

Here is the error.

```
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    === BUILD TARGET shared_preferences OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/user1/development/flutter/.pub-cache/hosted/pub.dartlang.org/image_downloader-0.11.2/ios/Classes/ImageDownloaderPlugin.m:2:9: fatal error: 'image_downloader/image_downloader-Swift.h' file not found
    #import <image_downloader/image_downloader-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

Could not build the application for the simulator.
Error launching application on iPhone XR.
```

We tried to build it on both the simulator and real device, getting the same error. This happened last week and we saw this issue, so we didn't bother to raise another issue.

Today we downloaded the latest built from Mar. 11, still having the same issue.

**Comment by ko2ic** [comment]
#12
