### ISSUE TITLE
ios flush close

### ISSUE THREAD

**Issue by 0-php** [ko2ic/image_downloader#24]
i use my demo and example imagedownlod in iphone6+ ios Flash back

**Comment by ko2ic** [comment]
@0-php What is happening concretely?

**Comment by 0-php** [comment]
mycode:
if i call this function my app will flash back nothing happening concretely
just Lost connection to device.
```dart
 Future<void> _downloadImage() async {
    String fileName;
    String path;
    int size;
    String mimeType;
    try {
      String imageId;
        imageId = await ImageDownloader.downloadImage("https://www.google.co.th/images/branding/googlelogo/2x/googlelogo_color_92x30dp.png");
      if (imageId == null) {
        return;
      }
      fileName = await ImageDownloader.findName(imageId);
      path = await ImageDownloader.findPath(imageId);
      size = await ImageDownloader.findByteSize(imageId);
      mimeType = await ImageDownloader.findMimeType(imageId);
    } on PlatformException catch (error) {
      print(error);
      setState(() {

      });
      return;
    }
  }

```

**Comment by ko2ic** [comment]
I tried it with the same URL and it worked.
It seems like there is a problem with your app.

Please tell me the environment of your app. (ie: ios version, emulator, ```flutter doctor -v```, and so on)

**Comment by 0-php** [comment]
@ko2ic 
➜  Documents flutter doctor -v
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale zh-Hans-CN)
    • Flutter version 1.2.1 at /Users/sam/flutter
    • Framework revision 8661d8aecd (9 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/sam/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/sam/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • iPhone X • E13B9970-10F6-468C-9A48-5ED4E9AB3EE7 • ios • iOS 12.1 (simulator)

! Doctor found issues in 1 category.

**Comment by ko2ic** [comment]
@0-php What is different from me is that the version of Xcode is 10.2.1.
Could you try version up of Xcode?

Also, I think you will get more detailed errors when running in Xcode, what about?
