### ISSUE TITLE
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.

### ISSUE THREAD

**Issue by k3sc** [ko2ic/image_downloader#28]
`D8: Program type already present: android.support.v4.os.ResultReceiver$MyResultReceiver

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: D:\flutter_projects\zdx_zqt\build\app\intermediates\transforms\dexBuilder\debug\52.jar, D:\flutter_projects\zdx_zqt\build\app\intermediates\transforms\dexBuilder\debug\60.jar, D:\flutter_projects\zdx_zqt\build\app\intermediates\transforms\dexBuilder\debug\69.jar, D:\flutter_projects\zdx_zqt\build\app\intermediates\transforms\dexBuilder\debug\70.jar, D:\flutter_projects\zdx_zqt\build\app\intermediates\transforms\dexBuilder\debug\54.jar, D:\flutter_projects\zdx_zqt\build\app\intermediates\transforms\dexBuilder\debug\67.jar, D:\flutter_projects\zdx_zqt\build\app\intermediates\transforms\dexBuilder\debug\42.jar, D:\flutter_projects\zdx_zqt\build\app\intermediates\transforms\dexBuilder\debug\72.jar, D:\flutter_projects\zdx_zqt\build\app\intermediates\transforms\dexBuilder\debug\48.jar, D:\flutter_projects\zdx_zqt\build\app\intermediates\transforms\dexBuilder\debug\74.jar, D:\flutter_projects\zdx_zqt\build\app\intermediates\transforms\dexBuilder\debug\57.jar, D:\flutter_projects\zdx_zqt\build\app\intermediates\transforms\dexBuilder\debug\63.jar, D:\flutter_projects\zdx_zqt\build\app\intermediates\transforms\dexBuilder\debug\43.jar, D:\flutter_projects\zdx_zqt\build\app\intermediates\transforms\dexBuilder\debug\61.jar, D:\flutter_projects\zdx_zqt\build\app\intermediates\transforms\dexBuilder\debug\55.jar, D:\flutter_projects\zdx_zqt\build\app\intermediates\transforms\dexBuilder\debug\73.jar, D:\flutter_projects\zdx_zqt\build\app\intermediates\transforms\dexBuilder\debug\49.jar, D:\flutter_projects\zdx_zqt\build\app\intermediates\transforms\dexBuilder\debug\58.jar, D:\flutter_projects\zdx_zqt\build\app\intermediates\transforms\dexBuilder\debug\39.jar, D:\flutter_projects\zdx_zqt\build\app\intermediates\transforms\dexBuilder\debug\40.jar, D:\flutter_projects\zdx_zqt\build\app\intermediates\transforms\dexBuilder\debug\66.jar, D:\flutter_projects\zdx_zqt\build\app\intermediates\transforms\dexBuilder\debug\75.jar, D:\flutter_projects\zdx_zqt\build\app\intermediates\transforms\dexBuilder\debug\64.jar, D:\flutter_projects\zdx_zqt\build\app\intermediates\transforms\dexBuilder\debug\14.jar, D:\flutter_projects\zdx_zqt\build\app\intermediates\transforms\dexBuilder\debug\13.jar, D:\flutter_projects\zdx_zqt\build\app\intermediates\transforms\dexBuilder\debug\7.jar, D:\flutter_projects\zdx_zqt\build\app\intermediates\transforms\dexBuilder\debug\19.jar, D:\flutter_projects\zdx_zqt\build\app\intermediates\transforms\dexBuilder\debug\3.jar, D:\flutter_projects\zdx_zqt\build\app\intermediates\transforms\dexBuilder\debug\10.jar, D:\flutter_projects\zdx_zqt\build\app\intermediates\transforms\dexBuilder\debug\18.jar, D:\flutter_projects\zdx_zqt\build\app\intermediates\transforms\dexBuilder\debug\8.jar, D:\flutter_projects\zdx_zqt\build\app\intermediates\transforms\dexBuilder\debug\4.jar, D:\flutter_projects\zdx_zqt\build\app\intermediates\transforms\dexBuilder\debug\11.jar, D:\flutter_projects\zdx_zqt\build\app\intermediates\transforms\dexBuilder\debug\9.jar, D:\flutter_projects\zdx_zqt\build\app\intermediates\transforms\dexBuilder\debug\5.jar, D:\flutter_projects\zdx_zqt\build\app\intermediates\transforms\dexBuilder\debug\17.jar, D:\flutter_projects\zdx_zqt\build\app\intermediates\transforms\dexBuilder\debug\15.jar, D:\flutter_projects\zdx_zqt\build\app\intermediates\transforms\dexBuilder\debug\20.jar, D:\flutter_projects\zdx_zqt\build\app\intermediates\transforms\dexBuilder\debug\2.jar, D:\flutter_projects\zdx_zqt\build\app\intermediates\transforms\dexBuilder\debug\12.jar, D:\flutter_projects\zdx_zqt\build\app\intermediates\transforms\dexBuilder\debug\6.jar, D:\flutter_projects\zdx_zqt\build\app\intermediates\transforms\dexBuilder\debug\16.jar
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: android.support.v4.os.ResultReceiver$MyResultReceiver

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 8s
Finished with error: Gradle task assembleDebug failed with exit code 1
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
`

![image](https://user-images.githubusercontent.com/28189393/58000231-b77fb480-7b0a-11e9-8882-455c2f2daf78.png)
`def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
def keystorePropertiesFile = rootProject.file("key.properties")
def keystoreProperties = new Properties()
keystoreProperties.load(new FileInputStream(keystorePropertiesFile))

if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 28

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.yinet.***"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        ndk {
            abiFilters 'x86', 'armeabi-v7a'//, 'x86_64', 'mips', 'mips64', 'arm64-v8a','armeabi'
        }
        manifestPlaceholders = [
                JPUSH_PKGNAME: applicationId,
                JPUSH_APPKEY : "********", // NOTE: JPush 上注册的包名对应的 Appkey.
                JPUSH_CHANNEL: "developer-default", //暂时填写默认值即可.
        ]
    }

    signingConfigs {
        release {
            keyAlias 'yinet'
            keyPassword 'zd123456'
            storeFile file('key/zhengding.jks')
            storePassword 'zd123456'
        }
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.release
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}
`
![image](https://user-images.githubusercontent.com/28189393/58000270-d9793700-7b0a-11e9-8f57-b4064c3fbec0.png)

**Comment by ko2ic** [comment]
@k3sc This plugin supports androidx.
What error did you see and thought that this plug-in was the cause?

**Comment by ko2ic** [comment]
It is still working properly now.
There is no response so close.
If you still have problems, please give a different issue.

**Comment by exeptionerror** [comment]
All Possible working solution added[ [Solved] Gradle failure may have been because of AndroidX incompatibilities in this Flutter app](https://fluttercorner.com/gradle-failure-may-have-been-because-of-androidx-incompatibilities-in-this-flutter-app/)
