### ISSUE TITLE
iOS: Not able to download images in iOS iphone.

### ISSUE THREAD

**Issue by Preethamveigas** [ko2ic/image_downloader#29]
The app crashes when an app gets opened in and gets an error in 
[ImageDownloaderPlugin registerWithRegistrar:registrar];
How to resolve this issue in ios.

**Comment by ko2ic** [comment]
@Preethamveigas I tried but it works fine.

First, please check if there is a similar problem below.

https://github.com/ko2ic/image_downloader/wiki

**Comment by ko2ic** [comment]
It is still working properly now.
There is no response so close.
If you still have problems, please give a different issue.
