### ISSUE TITLE
firebase_core/firebase_auth packages prevents IOS app build

### ISSUE THREAD

**Issue by j1ato** [ko2ic/image_downloader#32]
I've found that when I import firebase_core/firebase_auth this prevents the example code from running:

`Launching lib/main.dart on iPhone Xʀ in debug mode...
Xcode build done.                                           33.2s
Configuring the default Firebase app...
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000104b926fb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x0000000104136ac5 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000104b92555 +[NSException raise:format:] + 197
	3   Runner                              0x00000001010b8e92 +[FIRApp configure] + 562
	4   Runner                              0x0000000101172bd6 -[FLTFirebaseAuthPlugin init] + 214
	5   Runner                              0x0000000101172988 +[FLTFirebaseAuthPlugin registerWithRegistrar:] + 184
	6   Runner                              0x0000000101060370 +[GeneratedPluginRegistrant registerWithRegistry:] + 112
	7   Runner                            <…>`

This is the error from my own project `Launching lib/main.dart on iPhone Xʀ in debug mode...
Xcode build done.                                            1.5s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    === BUILD TARGET firebase_auth OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/papaanthony/flutter/.pub-cache/hosted/pub.dartlang.org/image_downloader-0.16.0/ios/Classes/ImageDownloaderPlugin.m:2:10: fatal error: 'image_downloader/image_downloader-Swift.h' file not found
     #import <image_downloader/image_downloader-Swift.h>
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
Could not build the application for the simulator.
Error launching application on iPhone Xʀ.`

**Comment by ko2ic** [comment]
@j1ato Please read Troubleshooting.

This problem is on the flutter side, so all plugins created with swift have the same problem. 

https://github.com/ko2ic/image_downloader/wiki#your-appdelegate-is-the-case-of-objective-c

**Comment by ko2ic** [comment]
It closes because there is no new information and it works without problems.(In my project, I use this plugin with firebase_auth.)

If there is a problem, please let me know again.
