### ISSUE TITLE
Execution failed for task ':image_downloader:compileDebugKotlin'.

### ISSUE THREAD

**Issue by harpreetsi9h** [ko2ic/image_downloader#38]
I have defined this in pubspec.yaml 
image_downloader: ^0.16.2
when i run my project this error comes everytime:

* What went wrong:
Execution failed for task ':image_downloader:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by ohjs88** [comment]
Modify **build.gradle** file as shown below.

`
    //ext.kotlin_version = '1.2.71'
    ext.kotlin_version = '1.3.21'
`

**Comment by ko2ic** [comment]
@harpreetsi9h I don't know that information alone.
How about running with the following options as described in the error message?
```--stacktrace --info --scan```

Also, as @ ohjs88 says, an error will occur if the kotlin version is old.

For reference, it works fine in the sample and my project.

**Comment by ko2ic** [comment]
This can be solved by increasing the Kotlin version, so close it.

**Comment by Paradox2405** [comment]
My ext.kotlin version was 1.7.31 and i had to downgrade to 1.5.31 in order for the plugin to work.
More info> https://github.com/ko2ic/image_downloader/wiki#compilation-error-in-kotlin-random

**Comment by mszakacz** [comment]
`image_downloader` is not maintained for over 20 months. It uses the old ext.kotlin version (1.5.31).

In my case I need the latest ext.kotlin version so I cannot use this package.
