### ISSUE TITLE
Execution failed for task ':image_downloader:compileReleaseKotlin'.

### ISSUE THREAD

**Issue by lakshit1** [ko2ic/image_downloader#44]
I am using Image downloader 0.19.0.
Every time I try to compile my app i got the foolowing error 

`e: C:\Users\admin\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\image_downloader-0.19.0\android\src\main\kotlin\com\ko2ic\imagedownloader\ImageDownloaderPlugin.kt: (355, 41): Unresolved reference: random

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':image_downloader:compileReleaseKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org`

**Comment by lakshit1** [comment]
This error is also displaying in android studio.
![20190915_131653](https://user-images.githubusercontent.com/51991640/64918446-e73e8080-d7bb-11e9-941f-793636c1d80b.jpg)

**Comment by ko2ic** [comment]
@lakshit1 Please chnage Kotlin version of your app to 1.3 or higher.
