### ISSUE TITLE
Download image from a non-secured (HTTP) results in PlatformException - 400

### ISSUE THREAD

**Issue by Newbie012** [ko2ic/image_downloader#47]
I've noticed that when I try to download an image from a non-secured connection, I get a PlatformException (400), no matter if the domain/url exists or not.

In production, I'll have a secured connection in my backend, but in development, I use my localhost as the backend, and it's not https.

Any solutions?

**Comment by Newbie012** [comment]
Hello?

**Comment by ko2ic** [comment]
@Newbie012 
If you are on ios, please check ATS(App Transport Security).

**Comment by Newbie012** [comment]
@ko2ic I'm on Android

**Comment by ko2ic** [comment]
If you are on Android9, please check https://stackoverflow.com/questions/51902629/how-to-allow-all-network-connection-types-http-and-https-in-android-9-pie
