### ISSUE TITLE
Integrating  the plugin causes gradle failture immediately

### ISSUE THREAD

**Issue by abdu987** [ko2ic/image_downloader#55]
Launching lib\main.dart on Android SDK built for x86 in debug mode...
* Error running Gradle:
ProcessException: Process "C:\Users\boood\AndroidStudioProjects\firebase_neten\android\gradlew.bat" exited abnormally:

> Configure project :app
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
  Command: C:\Users\boood\AndroidStudioProjects\firebase_neten\android\gradlew.bat app:properties

Please review your Gradle project setup in the android/ folder.
Exited (sigterm)

**Comment by ko2ic** [comment]
@abdu987 Is there a library that doesn't support androidx?

**Comment by ko2ic** [comment]
I closed because there was little information and time passed.
And using a library that does not support androidX.
