### ISSUE TITLE
Execution failed for task ':image_downloader:compileDebugKotlin'.

### ISSUE THREAD

**Issue by xiebanglong** [ko2ic/image_downloader#56]
Launching lib/main.dart on SM G8870 in debug mode...
e: /home/xbl/software/flutter/.pub-cache/hosted/pub.flutter-io.cn/image_downloader-0.18.1/android/src/main/kotlin/com/ko2ic/imagedownloader/ImageDownloaderPlugin.kt: (355, 41): Unresolved reference: random

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':image_downloader:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Gradle task assembleDebug failed with exit code 1

**Comment by ko2ic** [comment]
Same as below.

https://github.com/ko2ic/image_downloader/issues/49
