### ISSUE TITLE
Run time error (Android)

### ISSUE THREAD

**Issue by 8013853290** [ko2ic/image_downloader#6]
C:\Users\user\.gradle\caches\transforms-1\files-1.1\core-1.0.1.aar\5fa504017df0cb8b948001bd21bf1b1c\res\values\values.xml:133:5-70: AAPT: error: resource android:attr/fontVariationSettings not found.
    
C:\Users\user\.gradle\caches\transforms-1\files-1.1\core-1.0.1.aar\5fa504017df0cb8b948001bd21bf1b1c\res\values\values.xml:133:5-70: AAPT: error: resource android:attr/ttcIndex not found.
    
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Failed to process resources, see aapt output above for details.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 23s
Gradle task assembleDebug failed with exit code 1

pls check.

**Comment by ko2ic** [comment]
@8013853290 
Since the current version is working steadily, I think there is something wrong with the application.   
For example, your application is depending on Plugin which depends on old support library.

Is there a similar result with a simple application that depend on image_downloader?
And please paste result of ```flutter doctor -v``` .

**Comment by maylortaylor** [comment]
I also get this issue when I use `image_downloader: ^0.11.1`
If i remove this dependency and all references to it in my code, my app builds and runs fine.

**Comment by ko2ic** [comment]
@maylortaylor Thank you for comment.

What is your compileSdkVersion?    
If it is 27, please set it to 28.

I feel the same as [this content](https://stackoverflow.com/questions/49208772/error-resource-androidattr-fontvariationsettings-not-found).

**Comment by maylortaylor** [comment]
My `compileSdkVersion` was set to 27.

Changing `compileSdkVersion` to 28 did fix the issue.

**Comment by ko2ic** [comment]
@8013853290   
If it is the same reason close it. How about that?
