### ISSUE TITLE
How to specific saved folder name?

### ISSUE THREAD

**Issue by jinfagang** [ko2ic/image_downloader#8]
Can it expose an interface to specific to save folder name?

**Comment by ko2ic** [comment]
@jinfagang The function does not exist in the current version.

**Comment by ko2ic** [comment]
For example, on Android, specifying to change the download destination to ```DIRECTORY_PICTURES``` , etc. can be easily fixed.   
Are you asking for such a fix?

**Comment by jinfagang** [comment]
@ko2ic thanks for you reply. As far as I know, this is the **only** lib provides saving images into album in flutter community. So I think if it can more customized that would be very helpful for developers using this functionality

**Comment by ko2ic** [comment]
@jinfagang About storage destination, What kind of concrete customization can you be happy with?

**Comment by jinfagang** [comment]
@ko2ic As for Android, it would be better to save into a specific folder sometimes (users may easy to find or make it be app_name folder). For iOS, it's of course album ok though

**Comment by ko2ic** [comment]
@jinfagang I see. I will refer to it. Thank you very match!!

**Comment by ko2ic** [comment]
@jinfagang Added features.
You can now specify the destination in the external storage.   
In Android development, in the case of internal storage, it is common to download to external storage once and move to internal, so it is not implemented.

I will close it once.
