### ISSUE TITLE
App crashes after downloading Image on Android 10

### ISSUE THREAD

**Issue by inshaf** [ko2ic/image_downloader#84]
Image is getting downloading but app crashes after. Check the log after image downloaded

D/image_downloader(20320): 0
D/image_downloader(20320): RequestResult(id=2879, remoteUri=https://raw.githubusercontent.com/wiki/ko2ic/image_downloader/images/flutter.png, localUri=file:///storage/emulated/0/DCIM/adzapp/test-1.jpg, mediaType=image/png, totalSize=64448, title=test-1.jpg, description=)
D/AndroidRuntime(20320): Shutting down VM
E/AndroidRuntime(20320): FATAL EXCEPTION: main
E/AndroidRuntime(20320): java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.DOWNLOAD_COMPLETE flg=0x10 pkg=test.pack (has extras) } in com.ko2ic.imagedownloader.Downloader$execute$1@130ce33
E/AndroidRuntime(20320): 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1566)
E/AndroidRuntime(20320): 	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
E/AndroidRuntime(20320): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(20320): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(20320): 	at android.os.Looper.loop(Looper.java:224)
E/AndroidRuntime(20320): 	at android.app.ActivityThread.main(ActivityThread.java:7548)
E/AndroidRuntime(20320): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(20320): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/AndroidRuntime(20320): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/AndroidRuntime(20320): Caused by: java.io.FileNotFoundException: /storage/emulated/0/DCIM/test/test.jpg: open failed: EACCES (Permission denied)
E/AndroidRuntime(20320): 	at libcore.io.IoBridge.open(IoBridge.java:496)
E/AndroidRuntime(20320): 	at java.io.FileInputStream.<init>(FileInputStream.java:159)
E/AndroidRuntime(20320): 	at com.ko2ic.imagedownloader.ImageDownloaderPlugin$CallbackImpl$granted$3.invoke(ImageDownloaderPlugin.kt:281)
E/AndroidRuntime(20320): 	at com.ko2ic.imagedownloader.ImageDownloaderPlugin$CallbackImpl$granted$3.invoke(ImageDownloaderPlugin.kt:200)
E/AndroidRuntime(20320): 	at com.ko2ic.imagedownloader.Downloader.resolveDownloadStatus(Downloader.kt:171)
E/AndroidRuntime(20320): 	at com.ko2ic.imagedownloader.Downloader.access$resolveDownloadStatus(Downloader.kt:14)
E/AndroidRuntime(20320): 	at com.ko2ic.imagedownloader.Downloader$execute$1.onReceive(Downloader.kt:33)
E/AndroidRuntime(20320): 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1556)
E/AndroidRuntime(20320): 	... 8 more
E/AndroidRuntime(20320): Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
E/AndroidRuntime(20320): 	at libcore.io.Linux.open(Native Method)
E/AndroidRuntime(20320): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
E/AndroidRuntime(20320): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
E/AndroidRuntime(20320): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
E/AndroidRuntime(20320): 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7447)
E/AndroidRuntime(20320): 	at libcore.io.IoBridge.open(IoBridge.java:482)
E/AndroidRuntime(20320): 	... 15 more
I/Process (20320): Sending signal. PID: 20320 SIG: 9
Lost connection to device.
Exited (sigterm)

**Comment by vivektopiya** [comment]
A quick fix for that is to add this code in the AndroidManifest.xml file:

    //This attribute is "false" by default on apps targeting Android Q. 
    <application android:requestLegacyExternalStorage="true"... >
 

You can read more about it here: https://developer.android.com/training/data-storage/compatibility

**Comment by ko2ic** [comment]
https://github.com/ko2ic/image_downloader/issues/63
