### ISSUE TITLE
Error while build apk

### ISSUE THREAD

**Issue by hushmand** [ko2ic/image_downloader#93]
A problem occurred evaluating root project 'image_downloader'.
> Failed to apply plugin [id 'com.android.library']
   > Minimum supported Gradle version is 5.4.1. Current version is 5.1.1. If using the gradle wrapper, try editing the distributionUrl in /home/user/.gradle/daemon/5.1.1/gradle/wrapper/gradle-wrapper.properties to gradle-5.4.1-all.zip

**Comment by hushmand** [comment]
Did anyone have this problem?

**Comment by ko2ic** [comment]
Correct it exactly as it is written in the error.
