### ISSUE TITLE
Migrate to Null Safety

### ISSUE THREAD

**Issue by SametSahin10** [ko2ic/image_downloader#94]
Hello, do you have any plans to support null safety?

**Comment by krokyze** [comment]
@SametSahin10 @GrahamDi I created a pull request with null safety supported #95 

While it's not merged you definitely would help @ko2ic with testing it:
```
image_downloader:
   git:
      url: git@github.com:krokyze/image_downloader.git
```

**Comment by GrahamDi** [comment]
Thanks for your efforts, Martin. 

TBH I am probably gonna pull this package from my app. The community has known about null safety coming for quite a while now so if a package's owner has not done anything about it to date then I don't get a warm, comfy feeling for any future support. 

Flutter 2.0 is making me take a more practical view on the packages I have been using and I am trying to reduce them or move to using only well supported ones or alternative mechanisms.

**Comment by ko2ic** [comment]
@krokyze Thank you your contributions!
I will merge / release after confirmation!

I'm sorry I didn't have time ...
